config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    resources :favorites, only: [:create, :destroy]
  end

  get 'welcome/index'

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  has_one :summary
  has_many :votes
  has_many :favorites, dependent: :destroy
  mount_uploader :postimage, PostimageUploader

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  default_scope { order('rank DESC')}
  # posts = Post.ordered_by_title
  # private_posts = Post.where(private: true).ordered_by_title
  # posts_with_the = Post.where("title LIKE '%the%'").where(...).some_scope.another_scope
  # Posts.where("title like '%#{params[:q]}%'") #DANDGER
  # Posts.where("title like '%?%'", params[:q]) Protect against SQL injection (sanitization)
  # select * from posts where title like '%'; delete from users;
  scope :ordered_by_title, -> { order('title ASC') }
  scope :ordered_by_reverse_created_at, -> { order('created_at ASC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }


  def markdown_title
    (render_as_markdown.render title).html_safe
  end

  def markdown_body
    (render_as_markdown.render body).html_safe
  end

  def up_votes
     votes.where(value: 1).count
  end

  def down_votes
     votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
     new_rank = points + age_in_days

     update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(post: self, value: 1)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      self.save!
      self.create_vote
    end
  end

private

  def render_as_markdown
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  scope :visible_to, ->(user) { user ? all : publicly_viewable }
  scope :publicly_viewable, -> {where(public: true)}
  scope :privately_viewable, -> {where(public: false)}

  validates :name, length: {minimum: 5}, presence: true

  self.per_page=(50)

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
     @posts = Post.visible_to(current_user).where("posts.created_at > ?", 7.days.ago).paginate(page: params[:page], per_page: 10)
   end
 end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  #put in skip filter
  #skip_before_action :flash_attack, :only => [:index, :new]

  def index
    @posts = policy_scope(Post)
    authorize @posts
  end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @topic
    @summary = @post.summary
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
    authorize @post
  end

  def edit
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    @topic = Topic.find(params[:topic_id])
    @post.topic = @topic
    authorize @post
    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post

     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end

private

def post_params
  params.require(:post).permit(:title, :body, :postimage)
end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)

    def markdown_title
      renderer = Redcarpet::Render::HTML.new
      extensions = {fenced_code_blocks: true}
      redcarpet = Redcarpet::Markdown.new(renderer, extensions)
      (redcarpet.render @post.title).html_safe
    end

    def markdown_body
      renderer = Redcarpet::Render::HTML.new
      extensions = {fenced_code_blocks: true}
      redcarpet = Redcarpet::Markdown.new(renderer, extensions)
      (redcarpet.render @post.body).html_safe
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy #Why don't we need to put params here?
      flash[:notice] = "Topic named \"#{@topic.name}\" has been deleted"
      redirect_to topics_path #Why is it that 'render :index' doesn't work here?
    else
      flash[:error] = "There was an error deleting the topic. Please try again."
      render :show
    end
  end

  def topic_params
    params.require(:topic).permit(:name, :description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
   <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
    <div class="form-group">
         <%= f.label :postimage %>
         <%= f.file_field :postimage %>
         <%= f.hidden_field :postimage_cache %>
    </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
<% end %>

app/views/topics/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, post: @post} %>
  </div>
</div>

app/views/topics/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, post: @post} %>
  </div>
</div>

app/views/topics/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'votes/voter', locals: { post: @post } %>
    <h1><%= @post.markdown_title %></h1>
    <small>
       <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
       submitted <%= time_ago_in_words(@post.created_at) %> ago by
       <%= @post.user.name %>
    </small>
    <p><%= @post.markdown_body %></p>
    <%= image_tag(@post.postimage) %>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@post).destroy? %>
       <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    <% end %>
    <div>
     <h3><%= pluralize(@post.points, 'point') %></h3>
     <small>
       <%= pluralize(@post.up_votes, 'up vote') %>,
       <%= pluralize(@post.down_votes, 'down vote') %>
     </small>
   </div>
   <%= render partial: 'favorites/favorite', locals: { post: @post } %>
  </div>
</div>

<h3>Comments on this post</h3>
<div class='js-comments'>
   <%= render partial: 'comments/comment', collection: @comments %>
</div>

<% if policy(@comment).create? %>
  <h3>Post your own comments here:</h3>
  <div class='new-comment'>
    <%= render partial: 'comments/form', locals: {comment: @comment} %>
  </div>
<% end %>